### ISSUE TITLE
Question about index.py

### ISSUE THREAD

**Issue by chococakes** [MDMCK10/atomic-pythonk#2]
Hey, I'm a rookie programmer aimlessly searching through github, and I was wondering for the `onmessage` function in the `index.py` file, would it be easier to use a dictionary and a loop for it? I'm not home at the moment so I could not test it, but I wanted to ask anyway. I may be wrong.

Also, you guys are hilarious.

**Comment by MDMCK10** [comment]
uh, i'll leave this one up to @HexadecimalPython and @ry00000 since i have no idea what you're talking about

**Comment by HexadecimalPython** [comment]
The on_message in that bot is completely a meme, you shouldn't pay attention to it, infact you should overwrite it, that was @MDMCK10 making a meme out of what was at the time, the new TOS of Discord.

@MDMCK10 he was talking about the Totally Compliant MSG Storing System.

**Comment by chococakes** [comment]
Ah, okay. Sorry to bother you lol

**Comment by HexadecimalPython** [comment]
Thank you for reporting that moron's shit code, I'll get to fixing it after he's doing doing fuckall.

**Comment by MDMCK10** [comment]
🤔
